# More with numpy

In [1]:
import numpy as np

In [2]:
arr1=np.array([[1,2,3],[4,5,6]])
arr2=np.array([[11,12,13],[14,15,16]])

# Stacking

In [7]:
arr1 

array([[1, 2, 3],
       [4, 5, 6]])

In [8]:
arr2

array([[11, 12, 13],
       [14, 15, 16]])

In [ ]:
# hstack() - Horizontal stack & vstack() - vartical stack

In [10]:
np.vstack((arr1,arr2))  # It will add the array in vertical side

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [11, 12, 13],
       [14, 15, 16]])

In [11]:
np.vstack((arr1,arr2,arr1,arr2))  

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [11, 12, 13],
       [14, 15, 16],
       [ 1,  2,  3],
       [ 4,  5,  6],
       [11, 12, 13],
       [14, 15, 16]])

In [14]:
np.hstack((arr1,arr2))   #It will add the array in horizontal right side

array([[ 1,  2,  3, 11, 12, 13],
       [ 4,  5,  6, 14, 15, 16]])

In [4]:
arr3=np.array([100,200,300])

In [20]:
np.vstack((arr1,arr3))

array([[  1,   2,   3],
       [  4,   5,   6],
       [100, 200, 300]])

In [5]:
np.hstack((arr1,arr3))

ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)

In [23]:
arr3

array([100, 200, 300])

In [2]:
import numpy as np
arr4=np.array([500,600,700])

In [24]:
#dstack
np.dstack((arr3,arr4))   #<- This will happened if the both mateix have same number of elements
# This will vertically stack both array and then transpose of it

array([[[100, 500],
        [200, 600],
        [300, 700]]])

# spliting
Break one array into multiple array

In [ ]:
#array_split()

In [25]:
arr3

array([100, 200, 300])

In [26]:
#array_split()
np.array_split(arr3,3)

[array([100]), array([200]), array([300])]

In [31]:
br= np.array_split(arr3,3)

In [32]:
br[0]

array([100])

In [5]:
np.array_split(arr4,3)

[array([500]), array([600]), array([700])]

In [7]:
x=np.array([[1,2,3],[4,5,6]])

In [8]:
np.array_split(x,2)

[array([[1, 2, 3]]), array([[4, 5, 6]])]

In [10]:
np.array_split(x,3)

[array([[1, 2, 3]]), array([[4, 5, 6]]), array([], shape=(0, 3), dtype=int32)]

In [6]:
np.array_split(arr3,8)  #here, there will be 3 array with values and the 4th will be empty array

[array([100]),
 array([200]),
 array([300]),
 array([], dtype=int32),
 array([], dtype=int32),
 array([], dtype=int32),
 array([], dtype=int32),
 array([], dtype=int32)]

In [35]:
np.array_split(arr3,2)   #here, it will give first 2 values in 1st array and another 1 value will be given in 2nd array 

[array([100, 200]), array([300])]

In [36]:
np.array_split(arr3,10)   #here, the first 3 array will be take the values and another 7 will be remain empty

[array([100]),
 array([200]),
 array([300]),
 array([], dtype=int32),
 array([], dtype=int32),
 array([], dtype=int32),
 array([], dtype=int32),
 array([], dtype=int32),
 array([], dtype=int32),
 array([], dtype=int32)]

In [37]:
arr1

array([[1, 2, 3],
       [4, 5, 6]])

In [38]:
np.array_split(arr1,4)

[array([[1, 2, 3]]),
 array([[4, 5, 6]]),
 array([], shape=(0, 3), dtype=int32),
 array([], shape=(0, 3), dtype=int32)]

In [39]:
np.array_split(arr1,6)

[array([[1, 2, 3]]),
 array([[4, 5, 6]]),
 array([], shape=(0, 3), dtype=int32),
 array([], shape=(0, 3), dtype=int32),
 array([], shape=(0, 3), dtype=int32),
 array([], shape=(0, 3), dtype=int32)]

# searching

In [16]:
arr=np.array([1,2,3,4,5,6,3,3])

In [17]:
arr

array([1, 2, 3, 4, 5, 6, 3, 3])

In [48]:
#where
np.where(arr==3)   #It return the index number of the array where values will be 3

(array([2, 6, 7], dtype=int64),)

In [9]:
np.where(arr==25)

(array([], dtype=int64),)

In [50]:
np.where(arr<4)  #It gives the index of that elements which has value <4

(array([0, 1, 2, 6, 7], dtype=int64),)

In [52]:
arr1

array([[1, 2, 3],
       [4, 5, 6]])

In [51]:
np.where(arr1==4)

(array([1], dtype=int64), array([0], dtype=int64))

In [54]:
np.where(arr1==2)

(array([0], dtype=int64), array([1], dtype=int64))

# Sorting

In [11]:
newarr=np.array([10,5,6,-10,-7,20,0,4.5,18])

In [12]:
newarr

array([ 10. ,   5. ,   6. , -10. ,  -7. ,  20. ,   0. ,   4.5,  18. ])

In [57]:
np.sort(newarr)  #It will print the sorted array in ascending order

array([-10. ,  -7. ,   0. ,   4.5,   5. ,   6. ,  10. ,  18. ,  20. ])

In [60]:
#Descending
-np.sort(-newarr)   #It will print all the sorted array in descending order

array([ 20. ,  18. ,  10. ,   6. ,   5. ,   4.5,   0. ,  -7. , -10. ])

# Any() & All()
->any of the particular value among these array will be satisfy with condition then, it will print true.

 ->if every elements of an array will satisfy the condition, then and then it will print true otherwise it will give false

In [63]:
newarr= np.array([2,4,6,8,9])

In [64]:
newarr

array([2, 4, 6, 8, 9])

In [65]:
np.any(newarr%2==0)  #any of the particular value among these array will be satisfy with condition then, it will print true. 

True

In [66]:
np.all(newarr%2==0)  #if every elements of an array will satisfy the condition, then and them it will print true otherwise it will give false

False

In [24]:
newarr= np.array([2,4,6,8,10])

In [69]:
np.all(newarr%2==0)

True

# Resize()

In [27]:
a = np.arange(12)

In [28]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [11]:
a.reshape(4,3)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [12]:
np.reshape(a,(3,4))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [73]:
np.reshape(a,(5,5))   #<- it will give an error because you can't reshape more than ele. size array

ValueError: cannot reshape array of size 12 into shape (5,5)

In [74]:
np.resize(a,(5,5))   # But,resize wil print the value with it's extra size and it will fill up the value with re again that numbers or repeat the numbers 

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11,  0,  1,  2],
       [ 3,  4,  5,  6,  7],
       [ 8,  9, 10, 11,  0]])

In [29]:
arr=np.array([[1,2,3],[4,5,6]])

In [31]:
np.resize(arr,(5,5))

array([[1, 2, 3, 4, 5],
       [6, 1, 2, 3, 4],
       [5, 6, 1, 2, 3],
       [4, 5, 6, 1, 2],
       [3, 4, 5, 6, 1]])

# Delete

In [32]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [ ]:
#delete(arr,obj,axis)

In [34]:
# for 1 D
np.delete(a,5)   # 5 will be deleted from the array

array([ 0,  1,  2,  3,  4,  6,  7,  8,  9, 10, 11])

In [35]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [37]:
delmat=np.array([[1,2,3],[3,3,6]])

In [38]:
delmat

array([[1, 2, 3],
       [3, 3, 6]])

In [39]:
# for 2D, the delete function will convert all the dimension array in 1D and also for every dimension except 1D, it will remove the element from the index
np.delete(delmat,3) #<- it will not permanent delete the element from the array also it will remove only 1st 3 from the array

array([1, 2, 3, 3, 6])

In [40]:
delmat

array([[1, 2, 3],
       [3, 3, 6]])

In [41]:
np.delete(delmat,1,axis=0)  # The whole 2nd row will be deleted

array([[1, 2, 3]])

In [16]:
np.delete(delmat,1,axis=1)   #All second column will be deleted

array([[1, 3],
       [4, 6]])

# LCM - Least Common Multiple

In [ ]:
lcm= least common multiple
# lcm(4,6) = 12

In [42]:
num1=25
num2=125
np.lcm(num1,num2)

125

In [43]:
num3=625

In [44]:
np.lcm(num1,num2,num3)   #<- it will give an error bcoz with this method, you can find lcm of any 2 numbers only, not 3.

TypeError: return arrays must be of ArrayType

In [46]:
newarr

array([ 2,  4,  6,  8, 10])

In [47]:
np.lcm(newarr)  #There are more than 2 values here, so it wil give an error

ValueError: invalid number of arguments

In [ ]:
# For do lcm more than 2 numbers, we will use reduce function

In [48]:
np.lcm.reduce((num1,num2,num3))

625

In [102]:
np.lcm.reduce(newarr)   #now, due to reduce function, we can find lcm of the function

120

# GCD - Greatest Common Devisior

In [105]:
a=6
b=9
#gcd() will be 3

In [106]:
np.gcd(a,b)

3

In [108]:
np.gcd.reduce((6,18,24))

6

In [109]:
np.gcd.reduce([6,18,24])

6

In [110]:
newarr

array([ 2,  4,  6,  8, 10])

In [111]:
np.gcd.reduce(newarr)

2

# Linear Eqaution

In [ ]:
3x + y =9
x + 2y = 8

In [50]:
a=np.array([[3,1],[1,2]])
b=np.array([9,8])

In [113]:
a

array([[3, 1],
       [1, 2]])

In [114]:
b

array([9, 8])

In [115]:
#np.linalg.solve(a,b)
np.linalg.solve(a,b)

array([2., 3.])

In [ ]:
4x + 2y=18
x + 3y = 7

In [51]:
a=np.array([[4,2],[1,3]])
b=np.array([18,7])

In [52]:
np.linalg.solve(a,b)

array([4., 1.])

# Quadretic equation

In [ ]:
x^2 + 4x = -4
x^2 + 4x + 4 = 0

In [117]:
coeff = np.array([1,4,4])  # write all the coefficient of the equation

In [118]:
np.roots(coeff)    # It gives the answer of the equation directly by using x= [-b +- (b^2-4ac)^1/2]/2a

array([-2., -2.])

In [120]:
a=np.array([[1,2,3],[4,5,6]])
b=np.array([[10,20,30],[40,50,60]])

In [123]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [124]:
b

array([[10, 20, 30],
       [40, 50, 60]])

In [121]:
np.dot(a,b)

ValueError: shapes (2,3) and (2,3) not aligned: 3 (dim 1) != 2 (dim 0)

In [122]:
np.vdot(a,b)   # It is known as vector dot 
# here vector dot mean 1*10+2*20+....6*60

910

Mean

In [125]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [126]:
np.mean(a)  #<it is average of array values (1+4+9+16+25+36)/6

3.5

# Weighted Mean

In [128]:
array=np.array([1,2,3,4])
weight= np.array([4,3,2,1])

(1*4+2*3+3*2+4*1)/(4+3+2+1)

2.0

In [129]:
#average(array,weights=weight)
np.average(array,weights=weight)

2.0

In [56]:
array=np.array([[1,2,3,4],[4,5,6,7]])
weight= np.array([4,5,6,7])

In [57]:
np.average(array,weights=weight)  # It won't work if the axis values or shapes are different

TypeError: Axis must be specified when shapes of a and weights differ.

In [ ]:
scipy is used for scientific calculation

In [131]:
arr= np.array([5,-10,2,4,20,0.4,6.5,-3.5,9])

In [132]:
np.sort(arr)

array([-10. ,  -3.5,   0.4,   2. ,   4. ,   5. ,   6.5,   9. ,  20. ])

# argsort()

In [134]:
arr

array([  5. , -10. ,   2. ,   4. ,  20. ,   0.4,   6.5,  -3.5,   9. ])

In [136]:
np.sort(arr)

array([-10. ,  -3.5,   0.4,   2. ,   4. ,   5. ,   6.5,   9. ,  20. ])

In [133]:
np.argsort(arr)  #it will print the index of arr in index of old arr  as example, here, -10 is at osition 0 in sorted array but it is at position 1 in simple old arr . so argsort shows 1 at place of -10 in sorted list

array([1, 7, 5, 2, 3, 0, 6, 8, 4], dtype=int64)

In [137]:
newarr

array([ 2,  4,  6,  8, 10])

In [138]:
newarr**2

array([  4,  16,  36,  64, 100], dtype=int32)

In [139]:
#sqrt

In [140]:
np.sqrt(newarr)   #<-- It will give root value of the array

array([1.41421356, 2.        , 2.44948974, 2.82842712, 3.16227766])

In [142]:
np.square(newarr)

array([  4,  16,  36,  64, 100], dtype=int32)

In [59]:
a=np.random.rand(1000000)

In [60]:
a

array([0.92177032, 0.51768169, 0.67213495, ..., 0.21816297, 0.1290136 ,
       0.96437868])

In [74]:
import time
j=time.time()
print(np.mean(a))
s=time.time()-j
print(s)

0.5002693390125905
0.002998828887939453


In [75]:
import time
j=time.time()
print(sum(a)/len(a))
s=time.time()-j
print(s)

0.5002693390125933
0.10600066184997559


In [81]:
del a  #<- This will delete whole array 

In [97]:
%autosave 120

Autosaving every 120 seconds
