# Numpy

Moduled -> Packages -> libraried -> Framework

In [ ]:
Numpy -> Numerical Python

In [ ]:
Numpy array is 50x faster than list

In [3]:
import numpy as np
import time

In [42]:
a=np.array([1,10])

In [43]:
a

array([ 1, 10])

In [49]:
a= np.random.rand(100000000)

In [50]:
a

array([0.03918802, 0.84803947, 0.71277938, ..., 0.46722051, 0.29350024,
       0.41777521])

In [51]:
time.time()

1668619105.6732779

In [52]:
# List
start=time.time()    # It will show or capture the presently time
mean_list = sum(a)/len(a)
print(time.time()- start)

10.736345767974854


In [53]:
#Numpy
start=time.time()
mean_np = np.mean(a)
print(time.time()-start)

0.2000737190246582


In [7]:
mean_np   #here both value of average are same but numpy takes very few time for it. Where as, list takes more time than numpy

0.5000146461275833

In [8]:
mean_list

0.500014646127636

In [12]:
time.time()

1629249504.1721337

In [ ]:
!pip install numpy   #<- pip install a package installer for python
for google colab and jupyter notebook,add ! at start. In othereditor, do not use ! for installing through pip

In [ ]:
open source means -> 1. free to use
                     2. source code should be available
# Google is not an open source site bcoz you can't able to watch the source code means backend work of its site.    

In [13]:
import numpy as np

In [15]:
np.__version__  #<- It shows the current version of numpy in pc

'1.19.5'

 # Operations through numpy

Initializing the Numpy array


In [1]:
# for list
lis= []

In [4]:
#for numpy
arr=np.array()

TypeError: array() missing required argument 'object' (pos 1)

In [5]:
# 0D (Zero Dimensional)
arr= np.array(4)

In [57]:
arr

array(4)

In [7]:
arr=np.array((1,2,3,4,5,6,7,8,9,10)) 

In [8]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [58]:
# 1D (One Dimensional)
arr=np.array([1,2,3,4,5,6,7,8,9,10]) 

In [59]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
# you can also define an array in () <- tuple bracket instead of square column [] . both can be applicable.

In [10]:
# 2D (Two DImensional)
arr = np.array([[1,2,3,4],[5,6,7,8]])
arr=np.array([[1,2,3,4,5],[5,6,7,8,9]])

In [11]:
arr

array([[1, 2, 3, 4, 5],
       [5, 6, 7, 8, 9]])

In [67]:
arr = np.array([[1,2,3,4],[5,6,7,8],[9,0,11,12]])

In [68]:
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9,  0, 11, 12]])

In [12]:
# 3D (Three Dimensional) - 3D dimensional array means multiple 2nd dimensional array
arr = np.array([[ [1,2,3,4],[5,6,7,8]],[[8,7,6,5],[4,3,2,1]]])

In [14]:
arr5=np.array([[
            [1,2,3,4],
            [5,6,7,8]],
        [[5,4,3,2],
         [9,8,7,6]
]])

In [15]:
arr5

array([[[1, 2, 3, 4],
        [5, 6, 7, 8]],

       [[5, 4, 3, 2],
        [9, 8, 7, 6]]])

In [72]:
arr

array([[[1, 2, 3, 4],
        [5, 6, 7, 8]],

       [[1, 3, 5, 7],
        [6, 8, 9, 4]]])

In [40]:
type(arr)     #<- it is not list but it is one type of ndarray of numpy

numpy.ndarray

# ndim attribute 
it will gonna return the dimensions of the array

In [73]:
arr = np.array([[ 
                 [1,2,3,4],
                 [5,6,7,8]
               ],[ 
                 [8,7,6,5],
                 [4,3,2,1]
               ]
])

In [74]:
arr.ndim

3

In [16]:
arr = np.array([[[1,2,3,4],[5,6,7,8],[9,0,11,12]]])

In [17]:
arr

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9,  0, 11, 12]]])

In [18]:
arr.ndim  #<-- it shows the dimension of an array

3

In [81]:
arr=np.array([1,2,3,4])

In [82]:
arr.ndim

1

In [83]:
arr=np.array([[[1,2,3,4]]])

In [85]:
arr

array([[[1, 2, 3, 4]]])

In [84]:
arr.ndim

3

# ndmin 
This will change the array in that dimension which you want

In [19]:
arr=np.array([1,2,3,4],ndmin=10)

In [20]:
k=list(arr)

In [21]:
k

[array([[[[[[[[[1, 2, 3, 4]]]]]]]]])]

In [50]:
arr.ndim  #<- now it will show as 10 dimension array

10

In [51]:
arr   #<-this is the 10 dimension array

array([[[[[[[[[[1, 2, 3, 4]]]]]]]]]])

In [89]:
arr=np.array([1],ndmin=10)

In [90]:
arr

array([[[[[[[[[[1]]]]]]]]]])

In [27]:
arr = np.array([[1,2,3,4],[5,6,7,8]],ndmin=2)

In [28]:
arr

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [102]:
arr.ndim

2

**Remember that you can convert 2 dimension array into his high dimension array but not in low dimension array. like, you can convert 2 dimension array in 10 dimension, using ndmin but you can't convert 2 dimension array in 1 dimension using ndmin.

# shape
It tells about the number of elements or the type of the array

In [29]:
arr = np.array([[1,2,3,4],
                [5,6,7,8],
                [9,0,11,12]])

In [30]:
arr.shape

(3, 4)

In [103]:
arr= np.array([1,2,3,4,5])  #here, it shows the size of an array is 5 because it has only 5 straight column in the array

In [104]:
arr.shape   

(5,)

In [36]:
j=np.array([ 
                 [1,2,3,4],
                 [5,6,7,8]
               ])

In [40]:
j.reshape(4,2)

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [41]:
j

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [33]:
arr = np.array([[ 
                 [1,2,3,4],
                 [5,6,7,8]
               ],[ 
                 [8,7,6,5],
                 [4,3,2,1]
               ]
])

In [35]:
arr

array([[[1, 2, 3, 4],
        [5, 6, 7, 8]],

       [[8, 7, 6, 5],
        [4, 3, 2, 1]]])

In [34]:
arr.shape  #<- here,1st 2 shows that how many 2 dimensional array you have. 2nd 2 shows that how many rows in one 2 dimensional array
           #third 4 shows the total column in the array   a

(2, 2, 4)

In [44]:
arr = np.array([[ 
                 [1,2,3,4],
                 [5,6,7,8]
               ],[ 
                 [8,7,6,5],
                 [4,3,2,1]
               ],[
                 [9,10,11,12],
                 [13,14,15,16]
]
])

In [46]:
arr.shape    #<- first 3 numbr shows the total number of 2nd dimension array. second 2 shows the no. of rows in every 2nd dimension array and third 4 shows the column in the array

(3, 2, 4)

In [47]:
arr = np.array([[ 
                 [1,2,3,4],
                 [5,6,7,8]
               ],[ 
                 [8,7,6,5],
                 [4,3,2,1]
               ]
],ndmin=10)

In [48]:
arr.shape  #<- it shows the total attribute as per size of its dimension

(1, 1, 1, 1, 1, 1, 1, 2, 2, 4)

In [49]:
arr

array([[[[[[[[[[1, 2, 3, 4],
               [5, 6, 7, 8]],

              [[8, 7, 6, 5],
               [4, 3, 2, 1]]]]]]]]]])

# dtype
It tell about the type of the data

In [76]:
arr = np.array([[1,2,3,4],
                [5,6,7,8],
                [9,0,11,12]])

In [77]:
arr.dtype

dtype('int32')

In [78]:
arr = np.array(["mangoes","apple","cherry"])

In [79]:
arr.dtype   #<-  It shows unicode. In mathamatics, strings can be called as in form of unicode

dtype('<U7')

In [ ]:
i - integer
s - string
b - boolean
c - complex
f - float

In [103]:
arr = np.array(["mangoes","apple","cherry",9.9])  #<- numpy can support hetrogeneous data

In [104]:
arr

array(['mangoes', 'apple', 'cherry', '9.9'], dtype='<U32')

In [105]:
arr = np.array([[1,2,3,4],
                [5,6,7,8],
                [9,0,11,12]], dtype='int16')

In [106]:
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9,  0, 11, 12]], dtype=int16)

In [107]:
arr.ndim

2

In [84]:
arr.dtype

dtype('int16')

In [ ]:
int16 int32 shows the space given to every integer

In [85]:
arr = np.array([[1,2,3,4],
                [5,6,7,8],
                [9,0,11,12]], dtype='S')

In [86]:
arr.dtype

dtype('S2')

In [87]:
arr = np.array([["1",2,3,4],
                [5,6,7,8],
                [9,0,11,12]])

In [88]:
arr.dtype

dtype('<U2')

# Size
It shows the total no. of elements inside the array

In [108]:
arr = np.array([[1,2,3,4],
                [5,6,7,8],
                [9,10,11,12]])

In [93]:
arr.size    #<- this size is an attribute

12

In [ ]:
#This following size is an function that which we take from numpy

In [ ]:
When you want to the number of elements from row or column
Syntax:-  np.size(name of ndarry, 1(row) & 0(column))

In [109]:
np.size(arr,1)

4

In [92]:
np.size(arr,0)

3

# Itemsize
It tells us about the length of the single element in bytes

In [55]:
arr = np.array([[1,2,3,4],
                [5,6,7,8],
                [9,0,11,12]],dtype='int8')

In [56]:
arr.itemsize    #<- each element has given these bytes of size

1

In [97]:
arr = np.array([[1,2,3,4],
                [5,6,7,8],
                [9,0,11,12]],dtype='int64')

In [98]:
arr.itemsize    #<- you have converted this element in 8 byte through dtype function

8

# nbytes
it gives the total number of bytes in the array

In [75]:
arr=np.array(["hii","Hello",2,4])

In [76]:
arr.itemsize

44

In [77]:
arr.nbytes     #(44*4(total number of elements)=176)

176

In [72]:
arr = np.array([[1,2,3,4],
                [5,6,7,8],
                [9,0,11,12]])

In [73]:
arr.itemsize

4

In [100]:
arr.nbytes   #<- each element has 8 bytes and total 12 elements in array. so total 12*8=96

96

In [96]:
arr = np.array([["1",2,3,4],
                [5,6,7,8],
                [9,0,11,12]])

In [97]:
arr

array([['1', '2', '3', '4'],
       ['5', '6', '7', '8'],
       ['9', '0', '11', '12']], dtype='<U11')

In [98]:
arr.itemsize   #<- it gives 8 bytes of size to every element though there are string inside the array

44

In [99]:
arr.nbytes

528

In [39]:
%autosave 120

Autosaving every 120 seconds
