# CRUD operation

In [1]:
import numpy as np

C - Create

In [2]:
#np.array()
arr = np.array([[1,2,3],[4,5,6]])

In [3]:
arr.ndim

2

In [ ]:
#You can use all array function while creating in [] or () also. Both will be valid for dimensions

In [ ]:
np.zeros is used to make 0 matrix
arr=np.zeros()
arr=np.zeros(shape of matrix you want to make)

In [10]:
#np.zeros()
arr = np.zeros((3,3))

In [16]:
arr

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [18]:
arr=np.zeros((10))   #<- it is 1 dimensional array

In [19]:
arr

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [20]:
arr=np.zeros((2,3),dtype="S2")

In [21]:
arr

array([[b'', b'', b''],
       [b'', b'', b'']], dtype='|S2')

In [ ]:
# np.ones()

In [23]:
arr = np.ones(10)

In [24]:
arr

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [20]:
arr = np.ones([3,4])

In [21]:
arr

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [22]:
arr = np.ones([3,4],dtype="int")

In [23]:
arr

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [28]:
arr=np.random.rand(10)

In [29]:
arr

array([0.71333807, 0.09137631, 0.12482091, 0.50457721, 0.60685913,
       0.9156016 , 0.32008004, 0.71175107, 0.59857661, 0.9638366 ])

In [31]:
#np.empty
arr=np.empty([2,2])   #<-- It will print any random value in given matrix. In small matrix, it puts any random value, where as in high size matrix, it mostly puts 0 or 1 randomly

In [32]:
arr

array([[2.12199579e-314, 9.76118064e-313],
       [4.42682819e-321, 6.95187041e-310]])

In [47]:
arr=np.empty([10,25])

In [48]:
arr

array([[1.52704392e-311, 1.52704287e-311, 1.51678153e-320,
                    nan, 1.15998412e-028, 2.44171989e+232,
        8.00801729e+159, 6.19319847e-071, 3.69852904e-033,
        1.05133356e-153, 7.48827232e-067, 8.04882561e-096,
        8.60680720e-067, 1.03007848e-071, 6.01347002e-154,
        6.01347002e-154, 2.91447100e+222, 1.79372133e-052,
        5.20267279e-090, 2.40523451e-057, 4.08786004e+179,
        1.81148474e-152, 2.36942783e-038, 8.60244358e-067,
        1.05250120e-153],
       [7.40331863e-038, 8.05977686e-096, 1.58794505e-047,
        5.63890302e-038, 6.01347002e-154, 1.19920990e-071,
        8.31859163e-072, 2.17462894e-076, 5.20459040e-090,
        1.30489229e-076, 2.78986021e+179, 1.81148476e-152,
        2.99063837e-067, 1.45216548e-047, 1.05220986e-153,
        2.58392283e-057, 8.52794449e-096, 9.05797951e-043,
        3.37609614e-057, 6.01347176e-154, 1.17554076e-047,
        5.20459411e-090, 1.57649840e-052, 3.75923460e+179,
        4.65002893e-086],
    

In [34]:
arr=np.empty([4,4])

In [35]:
arr

array([[6.23042070e-307, 4.67296746e-307, 1.69121096e-306,
        1.24610994e-306],
       [8.34441742e-308, 1.78022342e-306, 6.23058028e-307,
        9.79107872e-307],
       [6.89807188e-307, 7.56594375e-307, 6.23060065e-307,
        1.78021527e-306],
       [8.34454050e-308, 1.11261027e-306, 2.04712907e-306,
        1.33504432e-306]])

In [ ]:
#np.full()  <- it gives all the matrix with same values
arr = np.full(shape of matrix, value that you want to print)

In [49]:
arr=np.full((4,4),5)1

In [50]:
arr

array([[5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5]])

In [38]:
arr=np.full([3,3,4],8)

In [39]:
arr

array([[[8, 8, 8, 8],
        [8, 8, 8, 8],
        [8, 8, 8, 8]],

       [[8, 8, 8, 8],
        [8, 8, 8, 8],
        [8, 8, 8, 8]],

       [[8, 8, 8, 8],
        [8, 8, 8, 8],
        [8, 8, 8, 8]]])

In [ ]:
# np.eye() -> Identity Matrix
# remember that, for identity matrix and diagonal matrix, for the same value, the size of row and column should be same. so that's why we put here only 1 value for matrix shape.0
# here, no. of rows= no. of columns

In [52]:
arr = np.eye(5)

In [53]:
arr

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [ ]:
#np.diag()  <- diagonal matrix or square matrix 
for this matrix also number of columns= no. of rows
here, you don't need to give shape of matrix. the matrix will take it from the directly as no. of values

In [66]:
arr=np.diag([1,2,3])

In [67]:
arr

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [54]:
arr = np.diag([1,2,3,4,5,6,7])

In [55]:
arr

array([[1, 0, 0, 0, 0, 0, 0],
       [0, 2, 0, 0, 0, 0, 0],
       [0, 0, 3, 0, 0, 0, 0],
       [0, 0, 0, 4, 0, 0, 0],
       [0, 0, 0, 0, 5, 0, 0],
       [0, 0, 0, 0, 0, 6, 0],
       [0, 0, 0, 0, 0, 0, 7]])

In [56]:
arr = np.diag([1,2,3,4,5,6,7,8,9,10])

In [57]:
arr

array([[ 1,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  2,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  3,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  4,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  5,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  6,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  7,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  8,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  9,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0, 10]])

In [ ]:
# np.linspace()
Ex.  10,20,5    <- it means give me 5 elements in interval 10 to 20 in same 5 parts of interval  
#here 10 and 20 both are also included

In [58]:
arr=np.linspace(10,20,5)

In [59]:
arr

array([10. , 12.5, 15. , 17.5, 20. ])

In [62]:
arr=np.linspace(0,10,10)

In [63]:
arr

array([ 0.        ,  1.11111111,  2.22222222,  3.33333333,  4.44444444,
        5.55555556,  6.66666667,  7.77777778,  8.88888889, 10.        ])

In [61]:
arr=np.linspace(1,10,10)

In [62]:
arr

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [3]:
#np.random()
import numpy as np
arr= np.random.rand(10)  #<- it will gives any 10 random values between 0 to 1 
#or also you can write arr=np.random.random(10)

In [2]:
arr

array([0.80321731, 0.19569054, 0.92259582, 0.13958379, 0.26331334,
       0.1018081 , 0.54591423, 0.41231823, 0.59954373, 0.43218809])

In [68]:
#np.random()
arr=np.random.randint(15,25, size=(2,3))  #<- it will print any random value between 15 to 25, in which 15 and 25 both are also included

In [69]:
arr

array([[15, 15, 20],
       [24, 23, 24]])

In [ ]:
# np.arange()
arr=np.arange(start,stop,step)   #<- it is as same as range function in python
# you can make only 1 dimension array by using arange function after that, you can change it in 2 dimension

In [75]:
arr=np.arange(0,5)

In [76]:
arr

array([0, 1, 2, 3, 4])

In [78]:
arr = np.arange(1,12,2)

In [79]:
arr

array([ 1,  3,  5,  7,  9, 11])

In [15]:
arr=np.arange(2,14)

In [89]:
arr

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13])

In [16]:
arr.shape=(4,3)

In [17]:
arr

array([[ 2,  3,  4],
       [ 5,  6,  7],
       [ 8,  9, 10],
       [11, 12, 13]])

In [70]:
arr=np.arange(10,16).reshape(2,3) 

In [71]:
arr

array([[10, 11, 12],
       [13, 14, 15]])

In [73]:
# you can change the dimension of any array by using shape function but remember the new shape size will be as same as the old one
arr.shape=(3,2)

In [74]:
arr

array([[10, 11],
       [12, 13],
       [14, 15]])

# U -> Update

In [76]:
arr1= np.array([1,2,3,4,5])
arr2= np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])

In [97]:
#Indexing
#1D array
arr1[0]

1

In [98]:
arr1[4]

5

In [99]:
arr1[-1]

5

In [ ]:
#for 2D array

In [77]:
arr2

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [84]:
arr2[(1,0)]

5

In [101]:
arr2[(1,2)]     # here, you have to write the place of matrix in (). you can't write it's place in []
# and you have to surely write it in [] while indexing

7

In [85]:
arr2[(2,3)]

12

In [86]:
arr2[(2,3)] = 28  #<- it will change the value in the matrix

In [88]:
arr2

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 28]])

In [ ]:
# for 3D matrix

In [109]:
arr3= np.array([[[1,2,3,4],
                [5,6,7,8]],
               [[9,10,11,12],
               [13,14,15,16]]])

In [110]:
arr3[(0,1,1)]

6

In [116]:
arr3[(0,1,1)] = 23

In [117]:
arr3

array([[[ 1,  2,  3,  4],
        [ 5, 23,  7,  8]],

       [[ 9, 10, 11, 12],
        [13, 14, 15, 16]]])

In [ ]:
# Slicing

In [126]:
arr2

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 28]])

In [89]:
arr.shape

(3, 2)

In [130]:
arr2[1:]   #it gives value from row 2 to 3 which index is 1 and 2

array([[ 5,  6,  7,  8],
       [ 9, 10, 11, 28]])

In [131]:
arr2[1:2]   # it gives only value of row 2 or that row which index is 1

array([[5, 6, 7, 8]])

In [141]:
arr2[1,0:2]  #this will print the 2nd row's 1st and 2nd column value

array([5, 6])

In [132]:
arr3

array([[[ 1,  2,  3,  4],
        [ 5, 23,  7,  8]],

       [[ 9, 10, 11, 12],
        [13, 14, 15, 16]]])

In [134]:
arr3[0,1:]

array([[ 5, 23,  7,  8]])

In [139]:
arr3[0,1:2]  #<- you can write 

array([[ 5, 23,  7,  8]])

In [142]:
arr3[0,1,0:2]  #<- It will print the value from 2nd row's 5 to 23

array([ 5, 23])

In [143]:
#Or
arr3[0,1][0:2]

array([ 5, 23])

In [90]:
arr2

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 28]])

In [91]:
arr2[1]

array([5, 6, 7, 8])

In [92]:
arr2[(1,2)]

7

In [93]:
arr2[1][2]

7

In [144]:
#Quiz

#Create a matrix 3x4, 10 to 500 + elements should be evenly distributed

arr=np.linspace(10,500,12)

In [145]:
arr

array([ 10.        ,  54.54545455,  99.09090909, 143.63636364,
       188.18181818, 232.72727273, 277.27272727, 321.81818182,
       366.36363636, 410.90909091, 455.45454545, 500.        ])

In [ ]:
#you can only change the dimension of array when the elements can easily set in the matrix in which dimension you change

In [147]:
arr.shape = (3,4)   #or you can write   arr.reshape(3,4)

In [148]:
arr

array([[ 10.        ,  54.54545455,  99.09090909, 143.63636364],
       [188.18181818, 232.72727273, 277.27272727, 321.81818182],
       [366.36363636, 410.90909091, 455.45454545, 500.        ]])

In [149]:
arr.reshape(4,3)   # This can be also used for reshape the array

array([[ 10.        ,  54.54545455,  99.09090909],
       [143.63636364, 188.18181818, 232.72727273],
       [277.27272727, 321.81818182, 366.36363636],
       [410.90909091, 455.45454545, 500.        ]])

In [150]:
arr.reshape(12,1)   #<- it will print 2D array

array([[ 10.        ],
       [ 54.54545455],
       [ 99.09090909],
       [143.63636364],
       [188.18181818],
       [232.72727273],
       [277.27272727],
       [321.81818182],
       [366.36363636],
       [410.90909091],
       [455.45454545],
       [500.        ]])

In [151]:
arr.reshape(12)    #<-- it will print 1D array

array([ 10.        ,  54.54545455,  99.09090909, 143.63636364,
       188.18181818, 232.72727273, 277.27272727, 321.81818182,
       366.36363636, 410.90909091, 455.45454545, 500.        ])

In [155]:
arr.reshape(2,3,2)

array([[[ 10.        ,  54.54545455],
        [ 99.09090909, 143.63636364],
        [188.18181818, 232.72727273]],

       [[277.27272727, 321.81818182],
        [366.36363636, 410.90909091],
        [455.45454545, 500.        ]]])

In [156]:
arr.reshape(3,2,2)

array([[[ 10.        ,  54.54545455],
        [ 99.09090909, 143.63636364]],

       [[188.18181818, 232.72727273],
        [277.27272727, 321.81818182]],

       [[366.36363636, 410.90909091],
        [455.45454545, 500.        ]]])

In [157]:
# create a 7x9 matrix where all the elements are random

arr=np.random.rand(63).reshape(7,9)

In [158]:
arr

array([[0.61299601, 0.40632528, 0.39983414, 0.09263949, 0.16218734,
        0.66632405, 0.85996024, 0.62948191, 0.08652855],
       [0.3102128 , 0.62247023, 0.27952978, 0.21143223, 0.71350417,
        0.30198887, 0.517418  , 0.80127977, 0.22737356],
       [0.25021631, 0.08791443, 0.11940883, 0.53556311, 0.11933127,
        0.21511323, 0.38602198, 0.26377055, 0.81278608],
       [0.59708303, 0.99969839, 0.22751716, 0.37476856, 0.58496255,
        0.10861181, 0.27306837, 0.0062808 , 0.25084748],
       [0.33399234, 0.09630759, 0.64524992, 0.89230582, 0.95771504,
        0.23025997, 0.0339352 , 0.19559654, 0.84483493],
       [0.29311876, 0.40867112, 0.71556163, 0.7441805 , 0.4432545 ,
        0.55948409, 0.59722309, 0.53769852, 0.66636985],
       [0.66249669, 0.29188409, 0.21217924, 0.97110416, 0.80021184,
        0.3494277 , 0.11184872, 0.87946059, 0.65132281]])

In [94]:
arr2

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 28]])

In [95]:
arr4 = np.array([15,16,17,18])

In [96]:
arr4

array([15, 16, 17, 18])

In [97]:
# this following will give an error
arr2.append(arr4)

AttributeError: 'numpy.ndarray' object has no attribute 'append'

In [98]:
# this following will give an error
# arr2.extend(arr3)
# arr2.append(arr4)
np.append(arr2,arr4)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 28, 15, 16, 17, 18])

In [168]:
np.append([arr2],[arr4])

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 28, 15, 16, 17, 18])

In [99]:
np.sort(np.append(arr2,arr4))

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 15, 16, 17, 18, 28])

In [100]:
arrop= np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
arrop1= np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])

In [101]:
np.add(arrop,arrop1)

array([[ 2,  4,  6,  8],
       [10, 12, 14, 16],
       [18, 20, 22, 24]])

In [102]:
arrop + arrop1  #<- this will do the sum of an array

array([[ 2,  4,  6,  8],
       [10, 12, 14, 16],
       [18, 20, 22, 24]])

In [174]:
arrop1 + 10 # it will add 10 in every m=element of matrix

array([[11, 12, 13, 14],
       [15, 16, 17, 18],
       [19, 20, 21, 22]])

In [175]:
arrop1 / 10   

array([[0.1, 0.2, 0.3, 0.4],
       [0.5, 0.6, 0.7, 0.8],
       [0.9, 1. , 1.1, 1.2]])

In [176]:
arrop - 1 

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [177]:
arrop * 2

array([[ 2,  4,  6,  8],
       [10, 12, 14, 16],
       [18, 20, 22, 24]])

In [180]:
lis=[1,2,3]
lis + 2     # you can't do addition,subtraction etc. in list but in numpy, we can do these type of things
lis/2

TypeError: unsupported operand type(s) for /: 'list' and 'int'

In [181]:
arrop*arrop1   # this will multiply each ele. of arrop with each element of arrop1

array([[  1,   4,   9,  16],
       [ 25,  36,  49,  64],
       [ 81, 100, 121, 144]])

In [3]:
import numpy as np
x,y=input().split()
arr=np.arange(1,(int(x)*int(y))+1)  
print(arr.reshape(int(x),int(y)))

2 3
[1 2 3 4 5 6]
[[1 2 3]
 [4 5 6]]


In [63]:
%autosave 120

Autosaving every 120 seconds
