In [1]:
import numpy as np

In [3]:
arr1 = np.array([[1,2,3,4,5],[6,7,8,9,10]])
arr2 = np.array([[10,9,8,7,6],[5,4,3,2,1]])

In [4]:
arr1

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [5]:
arr2

array([[10,  9,  8,  7,  6],
       [ 5,  4,  3,  2,  1]])

# Mathematical Functions & Stats

In [ ]:
Addition -> Add two matrices or add an element to a matrix

In [7]:
arr1+arr2

array([[11, 11, 11, 11, 11],
       [11, 11, 11, 11, 11]])

In [6]:
#Adding an element
arr1+20

array([[21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [4]:
arr3=np.array([1,2])

In [10]:
arr3

array([1, 2])

In [7]:
arr3+8

array([ 9, 10])

In [11]:
arr3.ndim

1

In [5]:
arr1+arr3

ValueError: operands could not be broadcast together with shapes (2,5) (2,) 

In [13]:
arr4=np.array([1,2,3,4,5])

In [14]:
arr4.shape

(5,)

In [8]:
arr1

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [16]:
arr1+arr4   #<- here, arr4 will be add in both rows of arr1. It means all the values will be added.
# So, it shows that if you want to add element, both have either same no. of columns or both have same no. of rows 

array([[ 2,  4,  6,  8, 10],
       [ 7,  9, 11, 13, 15]])

In [17]:
arr5=np.array([[1],[2]])

In [10]:
arr5

array([[1],
       [2]])

In [19]:
arr1+arr5     #The both array has same number of rows, so it will be added. Here, row of arr5 is added in every element of arr1 

array([[ 2,  3,  4,  5,  6],
       [ 8,  9, 10, 11, 12]])

Subtraction -> it will subtract every element of array

In [21]:
arr1

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [22]:
arr2

array([[10,  9,  8,  7,  6],
       [ 5,  4,  3,  2,  1]])

In [23]:
arr1-arr2

array([[-9, -7, -5, -3, -1],
       [ 1,  3,  5,  7,  9]])

In [24]:
arr1-100

array([[-99, -98, -97, -96, -95],
       [-94, -93, -92, -91, -90]])

# Division

In [26]:
arr1

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [27]:
arr2

array([[10,  9,  8,  7,  6],
       [ 5,  4,  3,  2,  1]])

In [29]:
arr1/arr2

array([[ 0.1       ,  0.22222222,  0.375     ,  0.57142857,  0.83333333],
       [ 1.2       ,  1.75      ,  2.66666667,  4.5       , 10.        ]])

In [30]:
arr1/arr1

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [12]:
arr1//arr2     #It will print the quotient after deviding 

array([[ 0,  0,  0,  0,  0],
       [ 1,  1,  2,  4, 10]], dtype=int32)

In [14]:
arr1%arr2    # It will print the remainder after a1 devided by a2

array([[1, 2, 3, 4, 5],
       [1, 3, 2, 1, 0]], dtype=int32)

In [31]:
arr1/4    #<- All the elements will be devided by 4

array([[0.25, 0.5 , 0.75, 1.  , 1.25],
       [1.5 , 1.75, 2.  , 2.25, 2.5 ]])

# Multiplication

In [33]:
arr1

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [34]:
arr2

array([[10,  9,  8,  7,  6],
       [ 5,  4,  3,  2,  1]])

In [37]:
arr1*arr2

array([[10, 18, 24, 28, 30],
       [30, 28, 24, 18, 10]])

In [36]:
arr1**arr2    # It will be arr1 raise to arr2

array([[    1,   512,  6561, 16384, 15625],
       [ 7776,  2401,   512,    81,    10]], dtype=int32)

In [40]:
arr1 ** 2

array([[  1,   4,   9,  16,  25],
       [ 36,  49,  64,  81, 100]], dtype=int32)

# Mulitiplication - cross & dot

In [42]:
arr1

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [43]:
arr2

array([[10,  9,  8,  7,  6],
       [ 5,  4,  3,  2,  1]])

In [44]:
# cross Product
arr1*arr2    #<- this will multiply of every element of arr1 with arr2

array([[10, 18, 24, 28, 30],
       [30, 28, 24, 18, 10]])

In [ ]:
# here, arr1 = 2x5 and arr2 = 2x5 , so here dot product can not be happened because for dot product axb and bxc should be happened, and the resultant matrix will be axc  

In [42]:
arr1.dot(arr2)

ValueError: shapes (2,5) and (2,5) not aligned: 5 (dim 1) != 2 (dim 0)

In [43]:
arr3=np.array([[1,2],[3,4],[5,6],[7,8],[9,10]])

In [44]:
arr3.ndim

2

In [45]:
arr3.shape

(5, 2)

In [48]:
arr1

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [47]:
arr3

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [46]:
# arr1 & arr3 dot product can be possible because 2x5 and 5x2 gives result matrix 2x2
np.dot(arr1,arr3)
#or also you can write
arr1.dot(arr3)

array([[ 95, 110],
       [220, 260]])

In [50]:
np.dot(arr1,arr3)

array([[ 95, 110],
       [220, 260]])

In [53]:
np.matmul(arr1,arr3)   #<- it will also used to do dot product of 2 matrix

array([[ 95, 110],
       [220, 260]])

# Diterminent

In [ ]:
# square matrix -> No. of rows = No. of columns
# square matrix -> No. of rows & No. of columns = same

In [50]:
import numpy as np
arr = np.array([[-4,-10],[0,5]])

In [61]:
arr

array([[ -4, -10],
       [  0,   5]])

In [63]:
|arr|= |(-4*5) - (-10,0)| = |-20 - 0| = 20

In [ ]:
[   a    (-1)b      c]
[(-1)d       e  (-1)f]
[   g    (-1)h      i]

In [51]:
#np.linalg.det(arr)  linalg <- linear algebra
a=np.linalg.det(arr)

In [52]:
arr=abs(a)

In [53]:
arr

19.999999999999996

In [54]:
detarray = np.array([[-10,-4,-6],[2,4,6],[-9,6,5]])

In [55]:
detarray

array([[-10,  -4,  -6],
       [  2,   4,   6],
       [ -9,   6,   5]])

In [ ]:
 |detaray|=|-10(4*5-6*6)-(-4)(2*5-6*(-9)+ (-6)(2*6-4*-9)|

In [57]:
np.linalg.det(detarray)

127.99999999999986

In [58]:
arr8=np.array([[1,1,1],[1,1,1],[1,1,1]])

In [59]:
np.linalg.det(arr8)

0.0

# Inverse of a matrix

In [60]:
arr=np.array([[1,2],[3,4]])

In [61]:
arr

array([[1, 2],
       [3, 4]])

In [ ]:
Inverse= (1/det(mat)) * transpose(adj.matrix)

In [62]:
np.linalg.inv(arr)

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [63]:
arr.transpose()

array([[1, 3],
       [2, 4]])

In [64]:
np.transpose(arr)

array([[1, 3],
       [2, 4]])

In [65]:
abs(-5)

5

In [68]:
deter= np.linalg.det(arr)

In [69]:
deter

-2.0000000000000004

In [70]:
det = abs(deter)

In [86]:
det

2.0000000000000004

In [79]:
arr

array([[1, 2],
       [3, 4]])

In [77]:
arr.transpose()/deter

array([[-0.5, -1.5],
       [-1. , -2. ]])

# Reciprocal 
A matrix's all values are inverse is known as reciprocal matrix means  1/ele.

In [91]:
arrec=np.array([[10,20],[30,40]])

In [92]:
arrec

array([[10, 20],
       [30, 40]])

In [ ]:
# reciprocal means every element are divided
# like reciprocal of aarec = [[1/10,1/20],
#                             [1/30,1/40]]

In [93]:
np.reciprocal(arrec)    #<- it prints 0 because the answer is in int

array([[0, 0],
       [0, 0]], dtype=int32)

In [94]:
np.reciprocal(arrec, dtype="float")    #<- Now, it wil give the value in float and in point

array([[0.1       , 0.05      ],
       [0.03333333, 0.025     ]])

# Statistics

In [83]:
statarr = np.array([[20,-9,-40],[0,10,-1],[7,6,34]])

In [97]:
statarr

array([[ 20,  -9, -40],
       [  0,  10,  -1],
       [  7,   6,  34]])

max()  <- It returns the maximum no. of element from the array

In [98]:
np.max(statarr)

34

In [ ]:
#Or you can also write like this

In [8]:
statarr.max()

34

In [99]:
np.max(statarr, axis=0)  #<- remember that axis=0 means column and axis=1 means rows
# This will give the maximum value from each columns of array

array([20, 10, 34])

In [86]:
np.max(statarr,axis=1) # column

array([20, 10, 34])

In [10]:
statarr = np.array([[20,50,-40],[9,10,-1],[7,26,34]])

In [103]:
statarr

array([[ 20,  50, -40],
       [  9,  10,  -1],
       [  7,  26,  34]])

In [104]:
np.max(statarr, axis=1)   #<- It will give the max values from every rows because axis=1 means rows

array([50, 10, 34])

In [105]:
statarr

array([[ 20,  50, -40],
       [  9,  10,  -1],
       [  7,  26,  34]])

In [106]:
np.min(statarr)

-40

In [107]:
np.min(statarr, axis=0)  # axis=0 for column

array([  7,  10, -40])

In [108]:
np.min(statarr,axis=1)   #axis=1 for rows

array([-40,  -1,   7])

# sum()

In [89]:
statarr

array([[ 20,  -9, -40],
       [  0,  10,  -1],
       [  7,   6,  34]])

In [90]:
np.sum(statarr)   #it prints sum of all elements

27

In [97]:
arr1=np.array([[1,2,3],[4,5,6]])
arr2=np.array([[8,5,6],[4,5,6]])

In [ ]:
# or you can write like this

In [13]:
statarr.sum()

115

In [111]:
np.sum(statarr,axis=0)   #sum of every elements of column

array([36, 86, -7])

In [112]:
np.sum(statarr,axis=1)   #sum of every elements of rows

array([30, 18, 67])

# argmax() & argmin()

In [114]:
statarr

array([[ 20,  50, -40],
       [  9,  10,  -1],
       [  7,  26,  34]])

In [115]:
np.argmax(statarr)   #<- it gives the index number of maximum element number as per array number which start from 0

1

In [14]:
#OR
statarr.argmax()

1

In [121]:
np.argmin(statarr)

2

In [124]:
statarr[(2,1)]=100
statarr[(1,1)]=-100

In [127]:
statarr

array([[  20,   50,  -40],
       [   9, -100,   -1],
       [   7,  100,   34]])

In [128]:
# remember, for argmax function, array is like statarr=[20,50,-40,9,-100,-1,7,100,34]
np.argmax(statarr)  #<-here, 100 will come at index number 7 from starting to 0 index

7

In [130]:
np.argmin(statarr)  #<-here, -100 will come at index number 4 from starting to 0 index

4

In [132]:
np.argmax(statarr, axis=1)   #<- it vill give highest value index from every rows

array([1, 0, 1], dtype=int64)

In [133]:
np.argmax(statarr, axis=0)  #<- it vill give highest value index from every column

array([0, 2, 2], dtype=int64)

# around()

In [107]:
arr = np.array([0.51,0.98])

In [108]:
np.around(arr)  #It will round off of every element as per it's values

array([1., 1.])

In [16]:
arr= np.array([0.46,0.98])   #<- if value is less than or equal to 0.5, then it will print 0

In [17]:
np.around(arr)

array([0., 1.])

In [18]:
arr= np.array([0.5,0.98])

In [19]:
np.around(arr)

array([0., 1.])

In [110]:
np.around(arr,decimals=1)  #It will round of the value after 1 point of the element

array([0.5, 1. ])

In [111]:
arr=np.array([3.509,0.98])

In [112]:
np.around(arr, decimals=3)   # It will round of the value after 3 point of element

array([3.509, 0.98 ])

In [113]:
np.around(arr,decimals=2)  # It will round off  till 2 points after the element

array([3.51, 0.98])

In [115]:
np.around(arr,decimals=1)

array([3.5, 1. ])

# floor & ceil

In [146]:
a=np.array([-1.7,-4.2,4.6,-0.87])

In [147]:
np.floor(a)

array([-2., -5.,  4., -1.])

In [148]:
np.ceil(a)

array([-1., -4.,  5., -0.])

In [ ]:
# arr1+arr2 or you can write also np.add(arr1,arr2)

# copy and view

In [ ]:
# copy will copy the element and it will not reflect in new copied element if there will be some change in old matrix
# where as view will be effect in new element and also on old element if changes were happen in either new matrix or old matrix

In [149]:
arr

array([3.509, 0.98 ])

In [150]:
x=arr.copy()

In [151]:
x

array([3.509, 0.98 ])

In [152]:
x[0]=10

In [153]:
x

array([10.  ,  0.98])

In [154]:
arr    #<- there is no change in arr after changing the value of x

array([3.509, 0.98 ])

In [155]:
y=arr.view()

In [156]:
y

array([3.509, 0.98 ])

In [157]:
arr

array([3.509, 0.98 ])

In [158]:
y[0]=25

In [159]:
y

array([25.  ,  0.98])

In [160]:
arr    #<- here, due to view, we have changed the value in y, then also it change happened in arr

array([25.  ,  0.98])

# Iteration

In [161]:
arr

array([25.  ,  0.98])

In [162]:
for i in arr:
    print(i)

25.0
0.98


In [163]:
arr1

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [164]:
for i in arr1:
    print(i)      #<- it will print 2 list which contain 2 different rows

[1 2 3 4 5]
[ 6  7  8  9 10]


In [165]:
for i in arr1:    #<- This will print all the element of arr1 in one single line
    for j in i:
        print(j)
# But here, The complexity will be more due to 2 for loop        

1
2
3
4
5
6
7
8
9
10


In [167]:
for i in np.nditer(arr1):  #This nditer will print all the elements of array very easily and with good efficiency
    print(i)

1
2
3
4
5
6
7
8
9
10


In [169]:
for i in np.nditer(arr1[1]):    #It will print all the element which row is at index 1
    print(i)

6
7
8
9
10


In [69]:
%autosave 120

Autosaving every 120 seconds
